GET http://localhost:8080/projects/2/members HTTP/1.1

###

POST http://localhost:8080/projects/2/members HTTP/1.1
Content-Type: application/json

{
  "memberId": "1"
}

###

DELETE http://localhost:8080/projects/2/members/1 HTTP/1.1